CREATE ROLE app_user WITH LOGIN PASSWORD '${APP_PASSWORD}';
CREATE ROLE migrator WITH LOGIN PASSWORD '${MIGRATOR_PASSWORD}';

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE CONNECT ON DATABASE forum FROM PUBLIC;

GRANT CONNECT ON DATABASE forum TO app_admin, app_user, migrator;

GRANT USAGE, CREATE ON SCHEMA public TO migrator;
GRANT USAGE ON SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO app_user;
