CREATE ROLE app_user WITH LOGIN PASSWORD :'app_password';
CREATE ROLE migrator WITH LOGIN PASSWORD :'migrator_password';

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE CONNECT ON DATABASE forum FROM PUBLIC;

GRANT CONNECT ON DATABASE forum TO app_admin, app_user, migrator;

GRANT USAGE, CREATE ON SCHEMA public TO migrator;
GRANT USAGE ON SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE migrator IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_user;
