// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/koftamainee/ozon-bank-test-assigment/internal/domain"
)

type CommentPage struct {
	Items []*domain.Comment `json:"items"`
	Next  *string           `json:"next,omitempty"`
}

type CreateCommentInput struct {
	PostID   int64  `json:"postID"`
	ParentID *int64 `json:"parentID,omitempty"`
	Body     string `json:"body"`
}

type CreatePostInput struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type Mutation struct {
}

type PostPage struct {
	Items []*domain.Post `json:"items"`
	Next  *string        `json:"next,omitempty"`
}

type Query struct {
}

type Subscription struct {
}
