package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/koftamainee/ozon-bank-test-assigment/internal/auth"
	"github.com/koftamainee/ozon-bank-test-assigment/internal/domain"
	"github.com/koftamainee/ozon-bank-test-assigment/internal/store"
)

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *domain.Comment) (*domain.User, error) {
	u, err := r.users.Load(ctx, obj.AuthorID)
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &u, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input CreatePostInput) (*domain.Post, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, gqlError(ctx, domain.ErrUnauthorized)
	}
	p, err := r.forum.CreatePost(ctx, userID, domain.CreatePostInput{Title: input.Title, Body: input.Body})
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &p, nil
}

// SetCommentsAllowed is the resolver for the setCommentsAllowed field.
func (r *mutationResolver) SetCommentsAllowed(ctx context.Context, postID int64, allowed bool) (*domain.Post, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, gqlError(ctx, domain.ErrUnauthorized)
	}
	p, err := r.forum.SetCommentsAllowed(ctx, postID, userID, allowed)
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &p, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input CreateCommentInput) (*domain.Comment, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, gqlError(ctx, domain.ErrUnauthorized)
	}
	body, err := domain.NewCommentBody(input.Body)
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	c, err := r.forum.CreateComment(ctx, userID, domain.CreateCommentInput{
		PostID:   input.PostID,
		ParentID: input.ParentID,
		Body:     body,
	})
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &c, nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *domain.Post) (*domain.User, error) {
	u, err := r.users.Load(ctx, obj.AuthorID)
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &u, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *string) (*PostPage, error) {
	page, err := r.forum.ListPosts(ctx, derefInt(first), store.ParseCursor(derefString(after)))
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	items := make([]*domain.Post, 0, len(page.Items))
	for i := range page.Items {
		items = append(items, &page.Items[i])
	}
	return &PostPage{Items: items, Next: nextCursor(page.Next)}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id int64) (*domain.Post, error) {
	p, err := r.forum.GetPost(ctx, id)
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	return &p, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, postID int64, first *int, after *string) (*CommentPage, error) {
	page, err := r.forum.ListComments(ctx, postID, derefInt(first), store.ParseCursor(derefString(after)))
	if err != nil {
		return nil, gqlError(ctx, err)
	}
	items := make([]*domain.Comment, 0, len(page.Items))
	for i := range page.Items {
		items = append(items, &page.Items[i])
	}
	return &CommentPage{Items: items, Next: nextCursor(page.Next)}, nil
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID int64) (<-chan *domain.Comment, error) {
	if postID <= 0 {
		return nil, gqlError(ctx, domain.ErrInvalidID)
	}
	sub, unsubscribe := r.notifier.Subscribe(postID)
	subCtx, cancel := r.trackSub(ctx)
	out := make(chan *domain.Comment)
	go func() {
		defer close(out)
		defer unsubscribe()
		defer cancel()
		for {
			select {
			case c := <-sub:
				select {
				case out <- &c:
				case <-subCtx.Done():
					return
				}
			case <-subCtx.Done():
				return
			}
		}
	}()
	return out, nil
}

// Username is the resolver for the username field.
func (r *userResolver) Username(ctx context.Context, obj *domain.User) (string, error) {
	return obj.Username.String(), nil
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type (
	commentResolver      struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	postResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
	userResolver         struct{ *Resolver }
)
